In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
diabetes_df = pd.read_csv("Resources/merged.csv")
diabetes_df.head()

,Unnamed: 0,SEQN,diabetes,insulin,worry_food,food_not_last,balanced_meals,food_security,emergency_food,food_stamp,...,mod_work_activity,vig_work_activity,walk_bicycle,vig_rec_activity,mod_rec_activity,height_in,10lb_losses,diet_health,week_meals_not_home,month_frozen_food
0,0,93705.0,2,2,3.0,3.0,3.0,1.0,2.0,2.0,...,2,2,2,2,1,63.0,4,3.0,5.0,0.0
1,1,93711.0,2,2,3.0,3.0,3.0,1.0,2.0,2.0,...,2,2,1,1,1,69.0,5,2.0,4.0,0.0
2,2,93712.0,2,2,2.0,2.0,2.0,3.0,2.0,1.0,...,1,1,2,1,1,68.0,5,4.0,12.0,0.0
3,3,93713.0,2,2,3.0,3.0,3.0,1.0,2.0,2.0,...,2,2,1,2,1,70.0,5,4.0,0.0,3.0
4,4,93714.0,1,1,3.0,3.0,3.0,1.0,1.0,2.0,...,2,2,2,2,2,60.0,4,4.0,5.0,8.0

In [2]:
diabetes_df.nunique()

Unnamed: 0               3441
SEQN                     3441
diabetes                    3
insulin                     2
worry_food                  3
food_not_last               3
balanced_meals              3
food_security               4
emergency_food              2
food_stamp                  2
monthly_income             12
family_savings              2
grocery_transport           9
health_insurance            2
pulse                       2
bmi                       383
weight                    916
12mo_alcohol               11
many_drinks_regularly       2
minutes_sedentary          41
mod_work_activity           2
vig_work_activity           2
walk_bicycle                2
vig_rec_activity            2
mod_rec_activity            2
height_in                  31
10lb_losses                 5
diet_health                 5
week_meals_not_home        22
month_frozen_food          30
dtype: int64

In [3]:
# Drop the option 3 in the diabetes row

diabetes_df.drop(diabetes_df.index[diabetes_df['diabetes'] == 3], inplace=True)
diabetes_df.head()

,Unnamed: 0,SEQN,diabetes,insulin,worry_food,food_not_last,balanced_meals,food_security,emergency_food,food_stamp,...,mod_work_activity,vig_work_activity,walk_bicycle,vig_rec_activity,mod_rec_activity,height_in,10lb_losses,diet_health,week_meals_not_home,month_frozen_food
0,0,93705.0,2,2,3.0,3.0,3.0,1.0,2.0,2.0,...,2,2,2,2,1,63.0,4,3.0,5.0,0.0
1,1,93711.0,2,2,3.0,3.0,3.0,1.0,2.0,2.0,...,2,2,1,1,1,69.0,5,2.0,4.0,0.0
2,2,93712.0,2,2,2.0,2.0,2.0,3.0,2.0,1.0,...,1,1,2,1,1,68.0,5,4.0,12.0,0.0
3,3,93713.0,2,2,3.0,3.0,3.0,1.0,2.0,2.0,...,2,2,1,2,1,70.0,5,4.0,0.0,3.0
4,4,93714.0,1,1,3.0,3.0,3.0,1.0,1.0,2.0,...,2,2,2,2,2,60.0,4,4.0,5.0,8.0

In [4]:
diabetes_df = diabetes_df.drop(columns = ['Unnamed: 0', 'SEQN'])
diabetes_df

,diabetes,insulin,worry_food,food_not_last,balanced_meals,food_security,emergency_food,food_stamp,monthly_income,family_savings,...,mod_work_activity,vig_work_activity,walk_bicycle,vig_rec_activity,mod_rec_activity,height_in,10lb_losses,diet_health,week_meals_not_home,month_frozen_food
0,2,2,3.0,3.0,3.0,1.0,2.0,2.0,2.0,2.0,...,2,2,2,2,1,63.0,4,3.0,5.0,0.0
1,2,2,3.0,3.0,3.0,1.0,2.0,2.0,12.0,1.0,...,2,2,1,1,1,69.0,5,2.0,4.0,0.0
2,2,2,2.0,2.0,2.0,3.0,2.0,1.0,4.0,2.0,...,1,1,2,1,1,68.0,5,4.0,12.0,0.0
3,2,2,3.0,3.0,3.0,1.0,2.0,2.0,7.0,2.0,...,2,2,1,2,1,70.0,5,4.0,0.0,3.0
4,1,1,3.0,3.0,3.0,1.0,1.0,2.0,6.0,2.0,...,2,2,2,2,2,60.0,4,4.0,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3436,2,2,3.0,3.0,3.0,1.0,2.0,2.0,3.0,1.0,...,2,1,1,1,1,63.0,1,3.0,3.0,2.0
3437,2,2,3.0,3.0,3.0,1.0,2.0,1.0,12.0,1.0,...,1,1,2,2,2,72.0,5,5.0,6.0,0.0
3438,2,2,2.0,2.0,2.0,3.0,2.0,2.0,10.0,1.0,...,1,2,2,2,2,65.0,1,2.0,1.0,1.0
3439,2,2,3.0,3.0,3.0,1.0,2.0,2.0,7.0,2.0,...,2,2,2,2,1,69.0,1,2.0,1.0,0.0
3440,2,2,2.0,2.0,2.0,4.0,2.0,2.0,7.0,2.0,...,2,2,2,2,2,69.0,1,4.0,2.0,0.0

In [5]:
dummies_diabetes_df = pd.get_dummies(diabetes_df, dtype=float)
dummies_diabetes_df

,diabetes,insulin,worry_food,food_not_last,balanced_meals,food_security,emergency_food,food_stamp,monthly_income,family_savings,...,mod_work_activity,vig_work_activity,walk_bicycle,vig_rec_activity,mod_rec_activity,height_in,10lb_losses,diet_health,week_meals_not_home,month_frozen_food
0,2,2,3.0,3.0,3.0,1.0,2.0,2.0,2.0,2.0,...,2,2,2,2,1,63.0,4,3.0,5.0,0.0
1,2,2,3.0,3.0,3.0,1.0,2.0,2.0,12.0,1.0,...,2,2,1,1,1,69.0,5,2.0,4.0,0.0
2,2,2,2.0,2.0,2.0,3.0,2.0,1.0,4.0,2.0,...,1,1,2,1,1,68.0,5,4.0,12.0,0.0
3,2,2,3.0,3.0,3.0,1.0,2.0,2.0,7.0,2.0,...,2,2,1,2,1,70.0,5,4.0,0.0,3.0
4,1,1,3.0,3.0,3.0,1.0,1.0,2.0,6.0,2.0,...,2,2,2,2,2,60.0,4,4.0,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3436,2,2,3.0,3.0,3.0,1.0,2.0,2.0,3.0,1.0,...,2,1,1,1,1,63.0,1,3.0,3.0,2.0
3437,2,2,3.0,3.0,3.0,1.0,2.0,1.0,12.0,1.0,...,1,1,2,2,2,72.0,5,5.0,6.0,0.0
3438,2,2,2.0,2.0,2.0,3.0,2.0,2.0,10.0,1.0,...,1,2,2,2,2,65.0,1,2.0,1.0,1.0
3439,2,2,3.0,3.0,3.0,1.0,2.0,2.0,7.0,2.0,...,2,2,2,2,1,69.0,1,2.0,1.0,0.0
3440,2,2,2.0,2.0,2.0,4.0,2.0,2.0,7.0,2.0,...,2,2,2,2,2,69.0,1,4.0,2.0,0.0

In [6]:
y = dummies_diabetes_df["diabetes"].values
X = dummies_diabetes_df.drop(["diabetes"], axis=1).values
print(X)
print(y)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=50)

[[ 2.  3.  3. ...  3.  5.  0.]
 [ 2.  3.  3. ...  2.  4.  0.]
 [ 2.  2.  2. ...  4. 12.  0.]
 ...
 [ 2.  2.  2. ...  2.  1.  1.]
 [ 2.  3.  3. ...  2.  1.  0.]
 [ 2.  2.  2. ...  4.  2.  0.]]
[2 2 2 ... 2 2 2]

In [7]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [8]:
# Changed the number of hidden nodes

number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  10
hidden_nodes_layer2 = 20

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=3, activation="softmax"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 10)                280
_________________________________________________________________
dense_1 (Dense)              (None, 20)                220
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 63
=================================================================
Total params: 563
Trainable params: 563
Non-trainable params: 0
_________________________________________________________________

In [9]:
nn.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [10]:
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
79/79 [==============================] - 1s 5ms/step - loss: 0.8259 - accuracy: 0.6705
Epoch 2/100
79/79 [==============================] - 0s 4ms/step - loss: 0.5479 - accuracy: 0.8411
Epoch 3/100
79/79 [==============================] - 0s 4ms/step - loss: 0.4661 - accuracy: 0.8450
Epoch 4/100
79/79 [==============================] - 0s 4ms/step - loss: 0.4222 - accuracy: 0.8510: 0s - loss: 0.4583 - accura
Epoch 5/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3871 - accuracy: 0.8658
Epoch 6/100
79/79 [==============================] - 0s 4ms/step - loss: 0.3634 - accuracy: 0.8798
Epoch 7/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3499 - accuracy: 0.8810
Epoch 8/100
79/79 [==============================] - 0s 6ms/step - loss: 0.3417 - accuracy: 0.8818
Epoch 9/100
79/79 [==============================] - 0s 6ms/step - loss: 0.3357 - accuracy: 0.8822
Epoch 10/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3322 - accuracy: 0.8830
Epoch 11/100
79/79 [==============================] - 0s 6ms/step - loss: 0.3294 - accuracy: 0.8826
Epoch 12/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3261 - accuracy: 0.8830
Epoch 13/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3244 - accuracy: 0.8822
Epoch 14/100
79/79 [==============================] - 0s 4ms/step - loss: 0.3217 - accuracy: 0.8830
Epoch 15/100
79/79 [==============================] - 1s 6ms/step - loss: 0.3202 - accuracy: 0.8822
Epoch 16/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3185 - accuracy: 0.8834
Epoch 17/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3166 - accuracy: 0.8842
Epoch 18/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3159 - accuracy: 0.8838
Epoch 19/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3146 - accuracy: 0.8838
Epoch 20/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3117 - accuracy: 0.8850
Epoch 21/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3102 - accuracy: 0.8850
Epoch 22/100
79/79 [==============================] - 1s 8ms/step - loss: 0.3090 - accuracy: 0.8842
Epoch 23/100
79/79 [==============================] - 1s 10ms/step - loss: 0.3076 - accuracy: 0.8862
Epoch 24/100
79/79 [==============================] - 1s 10ms/step - loss: 0.3067 - accuracy: 0.8866
Epoch 25/100
79/79 [==============================] - 1s 8ms/step - loss: 0.3049 - accuracy: 0.8870
Epoch 26/100
79/79 [==============================] - 1s 9ms/step - loss: 0.3039 - accuracy: 0.8870
Epoch 27/100
79/79 [==============================] - 1s 9ms/step - loss: 0.3028 - accuracy: 0.8858: 0s - loss: 0.293
Epoch 28/100
79/79 [==============================] - 0s 5ms/step - loss: 0.3014 - accuracy: 0.8866
Epoch 29/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2999 - accuracy: 0.8882
Epoch 30/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2992 - accuracy: 0.8878
Epoch 31/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2983 - accuracy: 0.8878
Epoch 32/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2966 - accuracy: 0.8890
Epoch 33/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2966 - accuracy: 0.8918
Epoch 34/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2948 - accuracy: 0.8898
Epoch 35/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2939 - accuracy: 0.8918
Epoch 36/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2936 - accuracy: 0.8898
Epoch 37/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2918 - accuracy: 0.8930
Epoch 38/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2935 - accuracy: 0.8906
Epoch 39/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2902 - accuracy: 0.8930
Epoch 40/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2898 - accuracy: 0.8922
Epoch 41/100
79/79 [==============================] - 0s 6ms/step - loss: 0.2882 - accuracy: 0.8922
Epoch 42/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2878 - accuracy: 0.8926
Epoch 43/100
79/79 [==============================] - 0s 3ms/step - loss: 0.2879 - accuracy: 0.8906
Epoch 44/100
79/79 [==============================] - 0s 3ms/step - loss: 0.2871 - accuracy: 0.8930
Epoch 45/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2858 - accuracy: 0.8914: 0s - loss: 0.2865 - accuracy: 0.89
Epoch 46/100
79/79 [==============================] - 0s 6ms/step - loss: 0.2849 - accuracy: 0.8926
Epoch 47/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2849 - accuracy: 0.8918
Epoch 48/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2830 - accuracy: 0.8930
Epoch 49/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2840 - accuracy: 0.8922
Epoch 50/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2826 - accuracy: 0.8930
Epoch 51/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2831 - accuracy: 0.8930
Epoch 52/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2814 - accuracy: 0.8946
Epoch 53/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2800 - accuracy: 0.8938: 0s - loss: 0.2802 - accuracy: 0.89
Epoch 54/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2801 - accuracy: 0.8946
Epoch 55/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2799 - accuracy: 0.8946
Epoch 56/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2781 - accuracy: 0.8954
Epoch 57/100
79/79 [==============================] - 0s 3ms/step - loss: 0.2769 - accuracy: 0.8950
Epoch 58/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2769 - accuracy: 0.8946
Epoch 59/100
79/79 [==============================] - 0s 6ms/step - loss: 0.2769 - accuracy: 0.8974
Epoch 60/100
79/79 [==============================] - 0s 3ms/step - loss: 0.2750 - accuracy: 0.8974
Epoch 61/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2752 - accuracy: 0.8950
Epoch 62/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2748 - accuracy: 0.8982
Epoch 63/100
79/79 [==============================] - 0s 3ms/step - loss: 0.2724 - accuracy: 0.8994
Epoch 64/100
79/79 [==============================] - 0s 3ms/step - loss: 0.2722 - accuracy: 0.8970
Epoch 65/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2719 - accuracy: 0.8978
Epoch 66/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2712 - accuracy: 0.8982
Epoch 67/100
79/79 [==============================] - 0s 3ms/step - loss: 0.2706 - accuracy: 0.8978
Epoch 68/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2707 - accuracy: 0.8970
Epoch 69/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2694 - accuracy: 0.8986
Epoch 70/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2684 - accuracy: 0.8978
Epoch 71/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2683 - accuracy: 0.8974
Epoch 72/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2671 - accuracy: 0.8982
Epoch 73/100
79/79 [==============================] - 0s 6ms/step - loss: 0.2657 - accuracy: 0.8978
Epoch 74/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2656 - accuracy: 0.8978: 0s - loss: 0.2606 - accuracy:
Epoch 75/100
79/79 [==============================] - ETA: 0s - loss: 0.2642 - accuracy: 0.89 - 0s 5ms/step - loss: 0.2653 - accuracy: 0.8974
Epoch 76/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2647 - accuracy: 0.8990
Epoch 77/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2624 - accuracy: 0.9002
Epoch 78/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2644 - accuracy: 0.8970
Epoch 79/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2626 - accuracy: 0.8986
Epoch 80/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2612 - accuracy: 0.8974
Epoch 81/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2598 - accuracy: 0.8986
Epoch 82/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2594 - accuracy: 0.8994
Epoch 83/100
79/79 [==============================] - 0s 3ms/step - loss: 0.2590 - accuracy: 0.9010: 0s - loss: 0.2589 - accuracy: 0.90
Epoch 84/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2576 - accuracy: 0.9002
Epoch 85/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2580 - accuracy: 0.8998
Epoch 86/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2572 - accuracy: 0.8994
Epoch 87/100
79/79 [==============================] - 0s 3ms/step - loss: 0.2555 - accuracy: 0.9002
Epoch 88/100
79/79 [==============================] - 0s 3ms/step - loss: 0.2552 - accuracy: 0.9006
Epoch 89/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2541 - accuracy: 0.9014
Epoch 90/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2532 - accuracy: 0.9038
Epoch 91/100
79/79 [==============================] - 0s 6ms/step - loss: 0.2532 - accuracy: 0.9014
Epoch 92/100
79/79 [==============================] - 0s 6ms/step - loss: 0.2544 - accuracy: 0.9030
Epoch 93/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2520 - accuracy: 0.9026: 0s - loss: 0.2457 - accu
Epoch 94/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2519 - accuracy: 0.9026
Epoch 95/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2514 - accuracy: 0.9022
Epoch 96/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2520 - accuracy: 0.9050
Epoch 97/100
79/79 [==============================] - 0s 4ms/step - loss: 0.2507 - accuracy: 0.9034
Epoch 98/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2499 - accuracy: 0.9022
Epoch 99/100
79/79 [==============================] - ETA: 0s - loss: 0.2518 - accuracy: 0.90 - 0s 3ms/step - loss: 0.2499 - accuracy: 0.9054
Epoch 100/100
79/79 [==============================] - 0s 3ms/step - loss: 0.2484 - accuracy: 0.9069

In [11]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

27/27 - 1s - loss: 0.3996 - accuracy: 0.8719
Loss: 0.39960578083992004, Accuracy: 0.8718562722206116