In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
diabetes_df = pd.read_csv("Resources/merged.csv")
diabetes_df.head()

,Unnamed: 0,SEQN,diabetes,insulin,worry_food,food_not_last,balanced_meals,food_security,emergency_food,food_stamp,...,mod_work_activity,vig_work_activity,walk_bicycle,vig_rec_activity,mod_rec_activity,height_in,10lb_losses,diet_health,week_meals_not_home,month_frozen_food
0,0,93705.0,2,2,3.0,3.0,3.0,1.0,2.0,2.0,...,2,2,2,2,1,63.0,4,3.0,5.0,0.0
1,1,93711.0,2,2,3.0,3.0,3.0,1.0,2.0,2.0,...,2,2,1,1,1,69.0,5,2.0,4.0,0.0
2,2,93712.0,2,2,2.0,2.0,2.0,3.0,2.0,1.0,...,1,1,2,1,1,68.0,5,4.0,12.0,0.0
3,3,93713.0,2,2,3.0,3.0,3.0,1.0,2.0,2.0,...,2,2,1,2,1,70.0,5,4.0,0.0,3.0
4,4,93714.0,1,1,3.0,3.0,3.0,1.0,1.0,2.0,...,2,2,2,2,2,60.0,4,4.0,5.0,8.0

In [2]:
diabetes_df.nunique()

Unnamed: 0               3441
SEQN                     3441
diabetes                    3
insulin                     2
worry_food                  3
food_not_last               3
balanced_meals              3
food_security               4
emergency_food              2
food_stamp                  2
monthly_income             12
family_savings              2
grocery_transport           9
health_insurance            2
pulse                       2
bmi                       383
weight                    916
12mo_alcohol               11
many_drinks_regularly       2
minutes_sedentary          41
mod_work_activity           2
vig_work_activity           2
walk_bicycle                2
vig_rec_activity            2
mod_rec_activity            2
height_in                  31
10lb_losses                 5
diet_health                 5
week_meals_not_home        22
month_frozen_food          30
dtype: int64

In [3]:
diabetes_df = diabetes_df.drop(columns = ['worry_food', 'food_not_last', 'balanced_meals', 'food_security', 'emergency_food', 'food_stamp', 'monthly_income', 'family_savings',
'grocery_transport', 'health_insurance', 'pulse', 'bmi', 'weight', '12mo_alcohol', 'many_drinks_regularly', 'minutes_sedentary', 'mod_work_activity', 'vig_work_activity',
'walk_bicycle', 'vig_rec_activity', 'mod_rec_activity', 'height_in', '10lb_losses', 'diet_health', 'week_meals_not_home', 'month_frozen_food'])
diabetes_df

      Unnamed: 0      SEQN  diabetes  insulin
0              0   93705.0         2        2
1              1   93711.0         2        2
2              2   93712.0         2        2
3              3   93713.0         2        2
4              4   93714.0         1        1
...          ...       ...       ...      ...
3436        3436  102935.0         2        2
3437        3437  102943.0         2        2
3438        3438  102944.0         2        2
3439        3439  102947.0         2        2
3440        3440  102956.0         2        2

[3441 rows x 4 columns]

In [4]:
dummies_diabetes_df = pd.get_dummies(diabetes_df, dtype=float)
dummies_diabetes_df

      Unnamed: 0      SEQN  diabetes  insulin
0              0   93705.0         2        2
1              1   93711.0         2        2
2              2   93712.0         2        2
3              3   93713.0         2        2
4              4   93714.0         1        1
...          ...       ...       ...      ...
3436        3436  102935.0         2        2
3437        3437  102943.0         2        2
3438        3438  102944.0         2        2
3439        3439  102947.0         2        2
3440        3440  102956.0         2        2

[3441 rows x 4 columns]

In [5]:
# Change variable to insulin 

y = dummies_diabetes_df["insulin"].values
X = dummies_diabetes_df.drop(["insulin"], axis=1).values
print(X)
print(y)

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=80)

[[0.00000e+00 9.37050e+04 2.00000e+00]
 [1.00000e+00 9.37110e+04 2.00000e+00]
 [2.00000e+00 9.37120e+04 2.00000e+00]
 ...
 [3.43800e+03 1.02944e+05 2.00000e+00]
 [3.43900e+03 1.02947e+05 2.00000e+00]
 [3.44000e+03 1.02956e+05 2.00000e+00]]
[2 2 2 ... 2 2 2]

In [6]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [7]:
# Changed the number of hidden nodes

number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  2
hidden_nodes_layer2 = 4

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 2)                 8
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 12
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 5
=================================================================
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________

In [8]:
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [9]:
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
81/81 [==============================] - 1s 1ms/step - loss: 0.7330 - accuracy: 0.0376
Epoch 2/100
81/81 [==============================] - 0s 1ms/step - loss: 0.3844 - accuracy: 0.0395
Epoch 3/100
81/81 [==============================] - 0s 1ms/step - loss: 0.0816 - accuracy: 0.0395
Epoch 4/100
81/81 [==============================] - 0s 2ms/step - loss: -0.3158 - accuracy: 0.0395
Epoch 5/100
81/81 [==============================] - 0s 2ms/step - loss: -0.8353 - accuracy: 0.0395
Epoch 6/100
81/81 [==============================] - 0s 2ms/step - loss: -1.4765 - accuracy: 0.0395
Epoch 7/100
81/81 [==============================] - 0s 2ms/step - loss: -2.2416 - accuracy: 0.0395
Epoch 8/100
81/81 [==============================] - 0s 2ms/step - loss: -3.1498 - accuracy: 0.0395
Epoch 9/100
81/81 [==============================] - 0s 2ms/step - loss: -4.2360 - accuracy: 0.0395
Epoch 10/100
81/81 [==============================] - 0s 2ms/step - loss: -5.5399 - accuracy: 0.0395
Epoch 11/100
81/81 [==============================] - 0s 2ms/step - loss: -7.0937 - accuracy: 0.0395
Epoch 12/100
81/81 [==============================] - 0s 1ms/step - loss: -8.9247 - accuracy: 0.0395
Epoch 13/100
81/81 [==============================] - 0s 2ms/step - loss: -11.0534 - accuracy: 0.0395
Epoch 14/100
81/81 [==============================] - 0s 2ms/step - loss: -13.4944 - accuracy: 0.0395
Epoch 15/100
81/81 [==============================] - 0s 2ms/step - loss: -16.2611 - accuracy: 0.0395
Epoch 16/100
81/81 [==============================] - 0s 2ms/step - loss: -19.3604 - accuracy: 0.0395
Epoch 17/100
81/81 [==============================] - 0s 2ms/step - loss: -22.8104 - accuracy: 0.0395
Epoch 18/100
81/81 [==============================] - 0s 2ms/step - loss: -26.6170 - accuracy: 0.0395
Epoch 19/100
81/81 [==============================] - 0s 2ms/step - loss: -30.7861 - accuracy: 0.0395
Epoch 20/100
81/81 [==============================] - 0s 2ms/step - loss: -35.3206 - accuracy: 0.0395
Epoch 21/100
81/81 [==============================] - 0s 2ms/step - loss: -40.2436 - accuracy: 0.0395
Epoch 22/100
81/81 [==============================] - 0s 1ms/step - loss: -45.5436 - accuracy: 0.0395
Epoch 23/100
81/81 [==============================] - 0s 2ms/step - loss: -51.2426 - accuracy: 0.0395
Epoch 24/100
81/81 [==============================] - 0s 1ms/step - loss: -57.3352 - accuracy: 0.0395
Epoch 25/100
81/81 [==============================] - 0s 2ms/step - loss: -63.8373 - accuracy: 0.0395
Epoch 26/100
81/81 [==============================] - 0s 1ms/step - loss: -70.7472 - accuracy: 0.0395
Epoch 27/100
81/81 [==============================] - 0s 2ms/step - loss: -78.0701 - accuracy: 0.0395
Epoch 28/100
81/81 [==============================] - 0s 1ms/step - loss: -85.8252 - accuracy: 0.0395
Epoch 29/100
81/81 [==============================] - 0s 2ms/step - loss: -93.9923 - accuracy: 0.0395
Epoch 30/100
81/81 [==============================] - 0s 1ms/step - loss: -102.5885 - accuracy: 0.0395
Epoch 31/100
81/81 [==============================] - 0s 1ms/step - loss: -111.6258 - accuracy: 0.0395
Epoch 32/100
81/81 [==============================] - 0s 1ms/step - loss: -121.0931 - accuracy: 0.0395
Epoch 33/100
81/81 [==============================] - 0s 2ms/step - loss: -131.0067 - accuracy: 0.0395
Epoch 34/100
81/81 [==============================] - 0s 1ms/step - loss: -141.3575 - accuracy: 0.0395
Epoch 35/100
81/81 [==============================] - 0s 1ms/step - loss: -152.1652 - accuracy: 0.0395- ETA: 0s - loss: -152.1115 - accuracy: 0.037
Epoch 36/100
81/81 [==============================] - 0s 1ms/step - loss: -163.4221 - accuracy: 0.0395
Epoch 37/100
81/81 [==============================] - 0s 1ms/step - loss: -175.1367 - accuracy: 0.0395
Epoch 38/100
81/81 [==============================] - 0s 2ms/step - loss: -187.3203 - accuracy: 0.0395
Epoch 39/100
81/81 [==============================] - 0s 1ms/step - loss: -199.9471 - accuracy: 0.0395
Epoch 40/100
81/81 [==============================] - 0s 1ms/step - loss: -213.0608 - accuracy: 0.0395
Epoch 41/100
81/81 [==============================] - 0s 2ms/step - loss: -226.6213 - accuracy: 0.0395
Epoch 42/100
81/81 [==============================] - 0s 1ms/step - loss: -240.6782 - accuracy: 0.0395
Epoch 43/100
81/81 [==============================] - 0s 1ms/step - loss: -255.2132 - accuracy: 0.0395
Epoch 44/100
81/81 [==============================] - 0s 1ms/step - loss: -270.2258 - accuracy: 0.0395
Epoch 45/100
81/81 [==============================] - 0s 2ms/step - loss: -285.7173 - accuracy: 0.0395
Epoch 46/100
81/81 [==============================] - 0s 2ms/step - loss: -301.7151 - accuracy: 0.0395
Epoch 47/100
81/81 [==============================] - 0s 1ms/step - loss: -318.2051 - accuracy: 0.0395
Epoch 48/100
81/81 [==============================] - 0s 2ms/step - loss: -335.2035 - accuracy: 0.0395
Epoch 49/100
81/81 [==============================] - 0s 2ms/step - loss: -352.7100 - accuracy: 0.0395
Epoch 50/100
81/81 [==============================] - 0s 2ms/step - loss: -370.6871 - accuracy: 0.0395
Epoch 51/100
81/81 [==============================] - 0s 2ms/step - loss: -389.1835 - accuracy: 0.0395
Epoch 52/100
81/81 [==============================] - 0s 2ms/step - loss: -408.2163 - accuracy: 0.0395
Epoch 53/100
81/81 [==============================] - 0s 2ms/step - loss: -427.7520 - accuracy: 0.0395
Epoch 54/100
81/81 [==============================] - 0s 2ms/step - loss: -447.7904 - accuracy: 0.0395
Epoch 55/100
81/81 [==============================] - 0s 2ms/step - loss: -468.3776 - accuracy: 0.0395
Epoch 56/100
81/81 [==============================] - 0s 2ms/step - loss: -489.4998 - accuracy: 0.0395
Epoch 57/100
81/81 [==============================] - 0s 2ms/step - loss: -511.1483 - accuracy: 0.0395
Epoch 58/100
81/81 [==============================] - 0s 2ms/step - loss: -533.3307 - accuracy: 0.0395
Epoch 59/100
81/81 [==============================] - 0s 2ms/step - loss: -556.0167 - accuracy: 0.0395
Epoch 60/100
81/81 [==============================] - 0s 2ms/step - loss: -579.2815 - accuracy: 0.0395
Epoch 61/100
81/81 [==============================] - 0s 2ms/step - loss: -603.0511 - accuracy: 0.0395
Epoch 62/100
81/81 [==============================] - 0s 2ms/step - loss: -627.4113 - accuracy: 0.0395
Epoch 63/100
81/81 [==============================] - 0s 2ms/step - loss: -652.3104 - accuracy: 0.0395
Epoch 64/100
81/81 [==============================] - 0s 2ms/step - loss: -677.7266 - accuracy: 0.0395
Epoch 65/100
81/81 [==============================] - 0s 2ms/step - loss: -703.7685 - accuracy: 0.0395
Epoch 66/100
81/81 [==============================] - 0s 2ms/step - loss: -730.3446 - accuracy: 0.0395
Epoch 67/100
81/81 [==============================] - 0s 2ms/step - loss: -757.4650 - accuracy: 0.0395
Epoch 68/100
81/81 [==============================] - 0s 2ms/step - loss: -785.2054 - accuracy: 0.0395
Epoch 69/100
81/81 [==============================] - 0s 2ms/step - loss: -813.4945 - accuracy: 0.0395
Epoch 70/100
81/81 [==============================] - 0s 2ms/step - loss: -842.3604 - accuracy: 0.0395
Epoch 71/100
81/81 [==============================] - 0s 2ms/step - loss: -871.8165 - accuracy: 0.0395
Epoch 72/100
81/81 [==============================] - 0s 2ms/step - loss: -901.8462 - accuracy: 0.0395
Epoch 73/100
81/81 [==============================] - 0s 2ms/step - loss: -932.5366 - accuracy: 0.0395
Epoch 74/100
81/81 [==============================] - 0s 2ms/step - loss: -963.8067 - accuracy: 0.0395
Epoch 75/100
81/81 [==============================] - 0s 3ms/step - loss: -995.7191 - accuracy: 0.0395
Epoch 76/100
81/81 [==============================] - 0s 2ms/step - loss: -1028.1439 - accuracy: 0.0395
Epoch 77/100
81/81 [==============================] - 0s 2ms/step - loss: -1061.2122 - accuracy: 0.0395
Epoch 78/100
81/81 [==============================] - 0s 2ms/step - loss: -1094.8597 - accuracy: 0.0395
Epoch 79/100
81/81 [==============================] - 0s 2ms/step - loss: -1129.1957 - accuracy: 0.0395
Epoch 80/100
81/81 [==============================] - 0s 2ms/step - loss: -1164.0609 - accuracy: 0.0395
Epoch 81/100
81/81 [==============================] - 0s 2ms/step - loss: -1199.6602 - accuracy: 0.0395
Epoch 82/100
81/81 [==============================] - 0s 2ms/step - loss: -1235.8353 - accuracy: 0.0395
Epoch 83/100
81/81 [==============================] - 0s 2ms/step - loss: -1272.6100 - accuracy: 0.0395
Epoch 84/100
81/81 [==============================] - 0s 2ms/step - loss: -1310.0880 - accuracy: 0.0395
Epoch 85/100
81/81 [==============================] - 0s 2ms/step - loss: -1348.1283 - accuracy: 0.0395
Epoch 86/100
81/81 [==============================] - 0s 2ms/step - loss: -1386.8464 - accuracy: 0.0395
Epoch 87/100
81/81 [==============================] - 0s 2ms/step - loss: -1426.2335 - accuracy: 0.0395
Epoch 88/100
81/81 [==============================] - 0s 2ms/step - loss: -1466.2098 - accuracy: 0.0395
Epoch 89/100
81/81 [==============================] - 0s 2ms/step - loss: -1506.9509 - accuracy: 0.0395
Epoch 90/100
81/81 [==============================] - 0s 2ms/step - loss: -1548.2365 - accuracy: 0.0395
Epoch 91/100
81/81 [==============================] - 0s 2ms/step - loss: -1590.2422 - accuracy: 0.0395
Epoch 92/100
81/81 [==============================] - 0s 2ms/step - loss: -1632.9298 - accuracy: 0.0395: 0s - loss: -1645.7362 - accuracy:
Epoch 93/100
81/81 [==============================] - 0s 2ms/step - loss: -1676.3347 - accuracy: 0.0395
Epoch 94/100
81/81 [==============================] - 0s 2ms/step - loss: -1720.3641 - accuracy: 0.0395
Epoch 95/100
81/81 [==============================] - 0s 2ms/step - loss: -1765.1177 - accuracy: 0.0395
Epoch 96/100
81/81 [==============================] - 0s 2ms/step - loss: -1810.5562 - accuracy: 0.0395
Epoch 97/100
81/81 [==============================] - ETA: 0s - loss: -1848.2375 - accuracy: 0.04 - 0s 2ms/step - loss: -1856.6351 - accuracy: 0.0395
Epoch 98/100
81/81 [==============================] - 0s 3ms/step - loss: -1903.4287 - accuracy: 0.0395
Epoch 99/100
81/81 [==============================] - 0s 2ms/step - loss: -1950.9678 - accuracy: 0.0395
Epoch 100/100
81/81 [==============================] - 0s 2ms/step - loss: -1999.1886 - accuracy: 0.0395

In [10]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

27/27 - 0s - loss: -2.0328e+03 - accuracy: 0.0407
Loss: -2032.8299560546875, Accuracy: 0.04065040498971939